import { Achievement } from '../types/progression';

export const ACHIEVEMENTS_CONFIG: Omit<Achievement, 'unlocked' | 'progress'>[] = [
  // Betting Category
  {
    id: 'first_win',
    name: 'First Victory',
    description: 'Win your first battle',
    icon: '🎯',
    requirement: 1,
    category: 'betting',
    coinReward: 10,
  },
  {
    id: 'lucky_streak',
    name: 'Lucky Streak',
    description: 'Win 3 battles in a row',
    icon: '🍀',
    requirement: 3,
    category: 'betting',
    coinReward: 25,
  },
  {
    id: 'streak_master',
    name: 'Streak Master',
    description: 'Reach a 5-win streak',
    icon: '🔥',
    requirement: 5,
    category: 'betting',
    coinReward: 50,
  },
  {
    id: 'unbeatable',
    name: 'Unbeatable',
    description: 'Reach a 10-win streak',
    icon: '👑',
    requirement: 10,
    category: 'betting',
    coinReward: 100,
  },
  
  // Combat Category
  {
    id: 'brawler',
    name: 'Brawler',
    description: 'Witness 100 total collisions',
    icon: '💥',
    requirement: 100,
    category: 'combat',
    coinReward: 15,
  },
  {
    id: 'warmonger',
    name: 'Warmonger',
    description: 'Witness 500 total collisions',
    icon: '⚔️',
    requirement: 500,
    category: 'combat',
    coinReward: 40,
  },
  {
    id: 'combo_starter',
    name: 'Combo Starter',
    description: 'Achieve a 5x combo',
    icon: '🌟',
    requirement: 5,
    category: 'combat',
    coinReward: 20,
  },
  {
    id: 'combo_master',
    name: 'Combo Master',
    description: 'Achieve a 10x mega combo',
    icon: '💫',
    requirement: 10,
    category: 'combat',
    coinReward: 50,
  },
  {
    id: 'speedrunner',
    name: 'Speedrunner',
    description: 'Win a battle in under 10 seconds',
    icon: '⚡',
    requirement: 10,
    category: 'combat',
    coinReward: 30,
  },
  
  // Mastery Category
  {
    id: 'veteran',
    name: 'Veteran',
    description: 'Complete 10 battles',
    icon: '🎖️',
    requirement: 10,
    category: 'mastery',
    coinReward: 20,
  },
  {
    id: 'arena_legend',
    name: 'Arena Legend',
    description: 'Complete 50 battles',
    icon: '🏆',
    requirement: 50,
    category: 'mastery',
    coinReward: 75,
  },
  {
    id: 'coin_collector',
    name: 'Coin Collector',
    description: 'Earn 500 total coins',
    icon: '💰',
    requirement: 500,
    category: 'mastery',
    coinReward: 50,
  },
  {
    id: 'millionaire',
    name: 'Millionaire',
    description: 'Earn 1000 total coins',
    icon: '💎',
    requirement: 1000,
    category: 'mastery',
    coinReward: 100,
  },
  
  // Special Category
  {
    id: 'comeback_king',
    name: 'Comeback King',
    description: 'Win after losing streak',
    icon: '🔄',
    requirement: 1,
    category: 'special',
    coinReward: 25,
  },
  {
    id: 'perfect_prediction',
    name: 'Perfect Prediction',
    description: 'Win 5 games with correct bets',
    icon: '🔮',
    requirement: 5,
    category: 'special',
    coinReward: 40,
  },
];
