export const EMOJI_MAP = {
  rock: "🪨",
  paper: "📜",
  scissors: "✂️",
} as const;

export const SPAWN_PRESETS = [15, 20, 25] as const;

export const GAME_CONFIG = {
  // Physics
  BASE_ARENA_SIZE: 600,
  BASE_ENTITY_SIZE: 32,
  COLLISION_DAMPING: 0.8,
  
  // Boost System
  CLICK_COOLDOWN: 3000,
  BOOST_DURATION: 2000,
  BOOST_SPEED_MULT: 1.8,
  BOOST_REVERT_MULT: 1 / 1.8,
  
  // Combo System
  COMBO_TIMEOUT: 2000,
  COMBO_PARTICLE_THRESHOLD: 3,
  MAX_COMBO_PARTICLES: 10,
  MEGA_COMBO_THRESHOLD: 10,
  
  // Timing
  BETTING_TIME: 15,
  COUNTDOWN_DURATION: 3,
  SCALE_ANIMATION_DURATION: 250,
  SCALE_ANIMATION_COOLDOWN: 100,
  CONFETTI_DURATION: 600,
  CONFETTI_VICTORY_DURATION: 3000,
  
  // Animation
  SCALE_BOOST: 1.2,
  SCALE_COOLDOWN: 0.95,
  SCALE_SPEED: 0.25,
  SLOW_MOTION_FACTOR: 0.4,
  SLOW_MOTION_THRESHOLD: 5,
  
  // Responsive Breakpoints
  MOBILE_MAX_WIDTH: 640,
  TABLET_MAX_WIDTH: 1024,
  MOBILE_MAX_ARENA: 350,
  DESKTOP_MAX_ARENA: 600,
  
  // Reserved Space (UI)
  RESERVED_SPACE_LANDSCAPE: 140,
  RESERVED_SPACE_MOBILE: 200,
  RESERVED_SPACE_TABLET: 180,
  RESERVED_SPACE_DESKTOP: 200,
} as const;
